# Dependencies
markdown:            kramdown
highlighter:         rouge
gems:                ['jekyll-paginate']
kramdown:
  input:              GFM
  syntax_highlighter: rogue


# Permalinks
#
permalink:           pretty

# Setup
title:               neovintage
tagline:             'by Rimas Silkaitis'
description:         ''
url:                 http://neovintage.org
baseurl:             /
paginate:            5
sass:
  sass_dir:          _sass
  style:             compressed

# About/contact
author:
  name:              Rimas Silkaitis
  url:               https://twitter.com/neovintage
  email:             neovintage@gmail.com
  quora:             http://www.quora.com/Rimas-Silkaitis

# Custom vars
version:             1.0.0

github:
  repo:              https://github.com/neovintage/neovintage.github.io
